In [64]:
import numpy as np
import pandas as pd

In [65]:
ipl = pd.read_csv("matches.csv")
ipl.head()

,id,season,city,date,match_type,player_of_match,venue,team1,team2,toss_winner,toss_decision,winner,result,result_margin,target_runs,target_overs,super_over,method,umpire1,umpire2
0,335982,2007/08,Bangalore,2008-04-18,League,BB McCullum,M Chinnaswamy Stadium,Royal Challengers Bangalore,Kolkata Knight Riders,Royal Challengers Bangalore,field,Kolkata Knight Riders,runs,140.0,223.0,20.0,N,NaN,Asad Rauf,RE Koertzen
1,335983,2007/08,Chandigarh,2008-04-19,League,MEK Hussey,"Punjab Cricket Association Stadium, Mohali",Kings XI Punjab,Chennai Super Kings,Chennai Super Kings,bat,Chennai Super Kings,runs,33.0,241.0,20.0,N,NaN,MR Benson,SL Shastri
2,335984,2007/08,Delhi,2008-04-19,League,MF Maharoof,Feroz Shah Kotla,Delhi Daredevils,Rajasthan Royals,Rajasthan Royals,bat,Delhi Daredevils,wickets,9.0,130.0,20.0,N,NaN,Aleem Dar,GA Pratapkumar
3,335985,2007/08,Mumbai,2008-04-20,League,MV Boucher,Wankhede Stadium,Mumbai Indians,Royal Challengers Bangalore,Mumbai Indians,bat,Royal Challengers Bangalore,wickets,5.0,166.0,20.0,N,NaN,SJ Davis,DJ Harper
4,335986,2007/08,Kolkata,2008-04-20,League,DJ Hussey,Eden Gardens,Kolkata Knight Riders,Deccan Chargers,Deccan Chargers,bat,Kolkata Knight Riders,wickets,5.0,111.0,20.0,N,NaN,BF Bowden,K Hariharan

In [66]:
subjects = ["English", "Mathematics", "Science", "Computer Science", "Hindi"]
marks = [66 , 77 , 82 , 99 , 58]
pd.Series(subjects)
pd.Series(marks)

pd.Series(marks, index=subjects, name="students data")

English             66
Mathematics         77
Science             82
Computer Science    99
Hindi               58
Name: students data, dtype: int64

In [67]:
# marks.mean()

In [68]:
ipl.sample(5)

,id,season,city,date,match_type,player_of_match,venue,team1,team2,toss_winner,toss_decision,winner,result,result_margin,target_runs,target_overs,super_over,method,umpire1,umpire2
223,501247,2011,Bangalore,2011-05-08,League,CH Gayle,M Chinnaswamy Stadium,Royal Challengers Bangalore,Kochi Tuskers Kerala,Kochi Tuskers Kerala,bat,Royal Challengers Bangalore,wickets,9.0,126.0,20.0,N,NaN,Aleem Dar,SS Hazare
591,1082605,2017,Delhi,2017-04-15,League,CJ Anderson,Feroz Shah Kotla,Delhi Daredevils,Kings XI Punjab,Delhi Daredevils,bat,Delhi Daredevils,runs,51.0,189.0,20.0,N,NaN,YC Barde,Nitin Menon
64,392188,2009,Cape Town,2009-04-22,League,AC Gilchrist,Newlands,Royal Challengers Bangalore,Deccan Chargers,Deccan Chargers,bat,Deccan Chargers,runs,24.0,185.0,20.0,N,NaN,M Erasmus,AM Saheba
817,1254059,2021,Mumbai,2021-04-10,League,S Dhawan,"Wankhede Stadium, Mumbai",Chennai Super Kings,Delhi Capitals,Delhi Capitals,field,Delhi Capitals,wickets,7.0,189.0,20.0,N,NaN,AK Chaudhary,VK Sharma
666,1136591,2018,Bengaluru,2018-05-01,League,TG Southee,M.Chinnaswamy Stadium,Royal Challengers Bangalore,Mumbai Indians,Mumbai Indians,field,Royal Challengers Bangalore,runs,14.0,168.0,20.0,N,NaN,M Erasmus,Nitin Menon

In [69]:
ipl.value_counts()

id       season   city           date        match_type  player_of_match   venue                                                             team1                        team2                        toss_winner                  toss_decision  winner                       result   result_margin  target_runs  target_overs  super_over  method  umpire1                umpire2
336022   2007/08  Delhi          2008-05-17  League      DPMD Jayawardene  Feroz Shah Kotla                                                  Delhi Daredevils             Kings XI Punjab              Delhi Daredevils             bat            Kings XI Punjab              runs     6.0            89.0         8.0           N           D/L     AV Jayaprakash         RE Koertzen        1
980943   2016     Hyderabad      2016-04-26  League      AB Dinda          Rajiv Gandhi International Stadium, Uppal                         Sunrisers Hyderabad          Rising Pune Supergiants      Rising Pune Supergiants      field          Rising Pune Supergiants      runs     34.0           61.0         11.0          N           D/L     AY Dandekar            CK Nandan          1
1359476  2023     Chandigarh     2023-04-01  League      Arshdeep Singh    Punjab Cricket Association IS Bindra Stadium, Mohali, Chandigarh  Punjab Kings                 Kolkata Knight Riders        Kolkata Knight Riders        field          Punjab Kings                 runs     7.0            154.0        16.0          N           D/L     BNJ Oxenford           YC Barde           1
1136592  2018     Delhi          2018-05-02  League      RR Pant           Arun Jaitley Stadium                                              Delhi Daredevils             Rajasthan Royals             Rajasthan Royals             field          Delhi Daredevils             runs     4.0            151.0        12.0          N           D/L     CK Nandan              VK Sharma          1
1136578  2018     Kolkata        2018-04-21  League      KL Rahul          Eden Gardens                                                      Kolkata Knight Riders        Kings XI Punjab              Kings XI Punjab              field          Kings XI Punjab              wickets  9.0            125.0        13.0          N           D/L     A Deshmukh             C Shamshuddin      1
1136566  2018     Jaipur         2018-04-11  League      SV Samson         Sawai Mansingh Stadium                                            Rajasthan Royals             Delhi Daredevils             Delhi Daredevils             field          Rajasthan Royals             runs     10.0           71.0         6.0           N           D/L     KN Ananthapadmanabhan  Nitin Menon        1
1082648  2017     Bangalore      2017-05-17  Eliminator  NM Coulter-Nile   M Chinnaswamy Stadium                                             Sunrisers Hyderabad          Kolkata Knight Riders        Kolkata Knight Riders        field          Kolkata Knight Riders        wickets  7.0            48.0         6.0           N           D/L     AK Chaudhary           Nitin Menon        1
980999   2016     Bangalore      2016-05-18  League      V Kohli           M Chinnaswamy Stadium                                             Royal Challengers Bangalore  Kings XI Punjab              Kings XI Punjab              field          Royal Challengers Bangalore  runs     82.0           203.0        14.0          N           D/L     KN Ananthapadmanabhan  M Erasmus          1
980997   2016     Visakhapatnam  2016-05-17  League      AB Dinda          Dr. Y.S. Rajasekhara Reddy ACA-VDCA Cricket Stadium               Rising Pune Supergiants      Delhi Daredevils             Rising Pune Supergiants      field          Rising Pune Supergiants      runs     19.0           58.0         11.0          N           D/L     Nitin Menon            C Shamshuddin      1
980989   2016     Kolkata        2016-05-14  League      YK Pathan         Eden Gardens                                                      Kolkata Knight Riders        Rising Pune Supergiants      Rising Pune Supergiants      bat            Kolkata Knight Riders        wickets  8.0            66.0         9.0           N           D/L     A Nand Kishore         BNJ Oxenford       1
829807   2015     Hyderabad      2015-05-15  League      V Kohli           Rajiv Gandhi International Stadium, Uppal                         Sunrisers Hyderabad          Royal Challengers Bangalore  Sunrisers Hyderabad          bat            Royal Challengers Bangalore  wickets  6.0            81.0         6.0           N           D/L     AK Chaudhary           HDPK Dharmasena    1
336025   2007/08  Kolkata        2008-05-18  League      M Ntini           Eden Gardens                                                      Kolkata Knight Riders        Chennai Super Kings          Kolkata Knight Riders        bat            Chennai Super Kings          runs     3.0            53.0         8.0           N           D/L     Asad Rauf              K Hariharan        1
829743   2015     Visakhapatnam  2015-04-22  League      DA Warner         Dr. Y.S. Rajasekhara Reddy ACA-VDCA Cricket Stadium               Sunrisers Hyderabad          Kolkata Knight Riders        Kolkata Knight Riders        field          Sunrisers Hyderabad          runs     16.0           118.0        12.0          N           D/L     RK Illingworth         VA Kulkarni        1
733993   2014     Delhi          2014-05-10  League      DW Steyn          Feroz Shah Kotla                                                  Delhi Daredevils             Sunrisers Hyderabad          Sunrisers Hyderabad          field          Sunrisers Hyderabad          wickets  8.0            43.0         5.0           N           D/L     RM Deshpande           BNJ Oxenford       1
501255   2011     Bangalore      2011-05-14  League      CH Gayle          M Chinnaswamy Stadium                                             Royal Challengers Bangalore  Kolkata Knight Riders        Royal Challengers Bangalore  field          Royal Challengers Bangalore  wickets  4.0            102.0        13.0          N           D/L     RE Koertzen            RB Tiffin          1
501245   2011     Kolkata        2011-05-07  League      Iqbal Abdulla     Eden Gardens                                                      Kolkata Knight Riders        Chennai Super Kings          Chennai Super Kings          bat            Kolkata Knight Riders        runs     10.0           52.0         10.0          N           D/L     Asad Rauf              PR Reiffel         1
501215   2011     Kochi          2011-04-18  League      BB McCullum       Nehru Stadium                                                     Kochi Tuskers Kerala         Chennai Super Kings          Kochi Tuskers Kerala         field          Kochi Tuskers Kerala         wickets  7.0            135.0        17.0          N           D/L     K Hariharan            AL Hill            1
392214   2009     Centurion      2009-05-07  League      ML Hayden         SuperSport Park                                                   Chennai Super Kings          Kings XI Punjab              Chennai Super Kings          bat            Chennai Super Kings          runs     12.0           187.0        18.0          N           D/L     DJ Harper              TH Wijewardene     1
392186   2009     Durban         2009-04-21  League      CH Gayle          Kingsmead                                                         Kings XI Punjab              Kolkata Knight Riders        Kolkata Knight Riders        field          Kolkata Knight Riders        runs     11.0           69.0         9.2           N           D/L     DJ Harper              SD Ranade          1
392183   2009     Cape Town      2009-04-19  League      DL Vettori        Newlands                                                          Delhi Daredevils             Kings XI Punjab              Delhi Daredevils             field          Delhi Daredevils             wickets  10.0           54.0         6.0           N           D/L     MR Benson              SD Ranade          1
1370353  2023     Ahmedabad      2023-05-29  Final       DP Conway         Narendra Modi Stadium, Ahmedabad                                  Gujarat Titans               Chennai Super Kings          Chennai Super Kings          field          Chennai Super Kings          wickets  5.0            171.0        15.0          N           D/L     Nitin Menon            RJ Tucker          1
dtype: int64

In [70]:
ipl.count()

id                 1095
season             1095
city               1044
date               1095
match_type         1095
player_of_match    1090
venue              1095
team1              1095
team2              1095
toss_winner        1095
toss_decision      1095
winner             1090
result             1095
result_margin      1076
target_runs        1092
target_overs       1092
super_over         1095
method               21
umpire1            1095
umpire2            1095
dtype: int64

In [71]:
mean = np.arange(24, 200)
mean.mean()
mean.max()
mean.std()

50.806003582253936

In [72]:
ipl.describe()

                 id  result_margin  target_runs  target_overs
count  1.095000e+03    1076.000000  1092.000000   1092.000000
mean   9.048283e+05      17.259294   165.684066     19.759341
std    3.677402e+05      21.787444    33.427048      1.581108
min    3.359820e+05       1.000000    43.000000      5.000000
25%    5.483315e+05       6.000000   146.000000     20.000000
50%    9.809610e+05       8.000000   166.000000     20.000000
75%    1.254062e+06      20.000000   187.000000     20.000000
max    1.426312e+06     146.000000   288.000000     20.000000

In [73]:
ipl.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1095 entries, 0 to 1094
Data columns (total 20 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   id               1095 non-null   int64
 1   season           1095 non-null   object
 2   city             1044 non-null   object
 3   date             1095 non-null   object
 4   match_type       1095 non-null   object
 5   player_of_match  1090 non-null   object
 6   venue            1095 non-null   object
 7   team1            1095 non-null   object
 8   team2            1095 non-null   object
 9   toss_winner      1095 non-null   object
 10  toss_decision    1095 non-null   object
 11  winner           1090 non-null   object
 12  result           1095 non-null   object
 13  result_margin    1076 non-null   float64
 14  target_runs      1092 non-null   float64
 15  target_overs     1092 non-null   float64
 16  super_over       1095 non-null   object
 17  method           21 non-null     object
 18  umpire1          1095 non-null   object
 19  umpire2          1095 non-null   object
dtypes: float64(3), int64(1), object(16)
memory usage: 171.2+ KB

In [74]:
# ipl(["player_of_the_match"])

In [75]:
import pandas as pd

data = [
    [56 , 87 , 98],
    [36 , 92 , 77],
    [64 , 82 , 44],
]
pd.DataFrame(data  , columns=["IQ", "MARKS", "PACKAGE"])

   IQ  MARKS  PACKAGE
0  56     87       98
1  36     92       77
2  64     82       44

In [76]:
ipl.shape
ipl.head()
ipl.columns
ipl.values
ipl.isnull()

,id,season,city,date,match_type,player_of_match,venue,team1,team2,toss_winner,toss_decision,winner,result,result_margin,target_runs,target_overs,super_over,method,umpire1,umpire2
0,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False
1,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False
2,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False
3,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False
4,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1090,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False
1091,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False
1092,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False
1093,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False
1094,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False

In [89]:
ipl.duplicated().sum()

# ipl["season", "city"]
ipl.iloc[:, 5]
# ipl.iloc[0:5]

0           BB McCullum
1            MEK Hussey
2           MF Maharoof
3            MV Boucher
4             DJ Hussey
             ...
1090    Abhishek Sharma
1091           MA Starc
1092           R Ashwin
1093      Shahbaz Ahmed
1094           MA Starc
Name: player_of_match, Length: 1095, dtype: object

In [90]:
# ipl.iloc(0, :, 5)
ipl.iloc[0:5]

,id,season,city,date,match_type,player_of_match,venue,team1,team2,toss_winner,toss_decision,winner,result,result_margin,target_runs,target_overs,super_over,method,umpire1,umpire2
0,335982,2007/08,Bangalore,2008-04-18,League,BB McCullum,M Chinnaswamy Stadium,Royal Challengers Bangalore,Kolkata Knight Riders,Royal Challengers Bangalore,field,Kolkata Knight Riders,runs,140.0,223.0,20.0,N,NaN,Asad Rauf,RE Koertzen
1,335983,2007/08,Chandigarh,2008-04-19,League,MEK Hussey,"Punjab Cricket Association Stadium, Mohali",Kings XI Punjab,Chennai Super Kings,Chennai Super Kings,bat,Chennai Super Kings,runs,33.0,241.0,20.0,N,NaN,MR Benson,SL Shastri
2,335984,2007/08,Delhi,2008-04-19,League,MF Maharoof,Feroz Shah Kotla,Delhi Daredevils,Rajasthan Royals,Rajasthan Royals,bat,Delhi Daredevils,wickets,9.0,130.0,20.0,N,NaN,Aleem Dar,GA Pratapkumar
3,335985,2007/08,Mumbai,2008-04-20,League,MV Boucher,Wankhede Stadium,Mumbai Indians,Royal Challengers Bangalore,Mumbai Indians,bat,Royal Challengers Bangalore,wickets,5.0,166.0,20.0,N,NaN,SJ Davis,DJ Harper
4,335986,2007/08,Kolkata,2008-04-20,League,DJ Hussey,Eden Gardens,Kolkata Knight Riders,Deccan Chargers,Deccan Chargers,bat,Kolkata Knight Riders,wickets,5.0,111.0,20.0,N,NaN,BF Bowden,K Hariharan

In [96]:
ipl.loc[0:2]

,id,season,city,date,match_type,player_of_match,venue,team1,team2,toss_winner,toss_decision,winner,result,result_margin,target_runs,target_overs,super_over,method,umpire1,umpire2
0,335982,2007/08,Bangalore,2008-04-18,League,BB McCullum,M Chinnaswamy Stadium,Royal Challengers Bangalore,Kolkata Knight Riders,Royal Challengers Bangalore,field,Kolkata Knight Riders,runs,140.0,223.0,20.0,N,NaN,Asad Rauf,RE Koertzen
1,335983,2007/08,Chandigarh,2008-04-19,League,MEK Hussey,"Punjab Cricket Association Stadium, Mohali",Kings XI Punjab,Chennai Super Kings,Chennai Super Kings,bat,Chennai Super Kings,runs,33.0,241.0,20.0,N,NaN,MR Benson,SL Shastri
2,335984,2007/08,Delhi,2008-04-19,League,MF Maharoof,Feroz Shah Kotla,Delhi Daredevils,Rajasthan Royals,Rajasthan Royals,bat,Delhi Daredevils,wickets,9.0,130.0,20.0,N,NaN,Aleem Dar,GA Pratapkumar

In [106]:
ipl.iloc[0:6 , 0:4]
ipl.loc[0:11, 'season' : 'winner']

,season,city,date,match_type,player_of_match,venue,team1,team2,toss_winner,toss_decision,winner
0,2007/08,Bangalore,2008-04-18,League,BB McCullum,M Chinnaswamy Stadium,Royal Challengers Bangalore,Kolkata Knight Riders,Royal Challengers Bangalore,field,Kolkata Knight Riders
1,2007/08,Chandigarh,2008-04-19,League,MEK Hussey,"Punjab Cricket Association Stadium, Mohali",Kings XI Punjab,Chennai Super Kings,Chennai Super Kings,bat,Chennai Super Kings
2,2007/08,Delhi,2008-04-19,League,MF Maharoof,Feroz Shah Kotla,Delhi Daredevils,Rajasthan Royals,Rajasthan Royals,bat,Delhi Daredevils
3,2007/08,Mumbai,2008-04-20,League,MV Boucher,Wankhede Stadium,Mumbai Indians,Royal Challengers Bangalore,Mumbai Indians,bat,Royal Challengers Bangalore
4,2007/08,Kolkata,2008-04-20,League,DJ Hussey,Eden Gardens,Kolkata Knight Riders,Deccan Chargers,Deccan Chargers,bat,Kolkata Knight Riders
5,2007/08,Jaipur,2008-04-21,League,SR Watson,Sawai Mansingh Stadium,Rajasthan Royals,Kings XI Punjab,Kings XI Punjab,bat,Rajasthan Royals
6,2007/08,Hyderabad,2008-04-22,League,V Sehwag,"Rajiv Gandhi International Stadium, Uppal",Deccan Chargers,Delhi Daredevils,Deccan Chargers,bat,Delhi Daredevils
7,2007/08,Chennai,2008-04-23,League,ML Hayden,"MA Chidambaram Stadium, Chepauk",Chennai Super Kings,Mumbai Indians,Mumbai Indians,field,Chennai Super Kings
8,2007/08,Hyderabad,2008-04-24,League,YK Pathan,"Rajiv Gandhi International Stadium, Uppal",Deccan Chargers,Rajasthan Royals,Rajasthan Royals,field,Rajasthan Royals
9,2007/08,Chandigarh,2008-04-25,League,KC Sangakkara,"Punjab Cricket Association Stadium, Mohali",Kings XI Punjab,Mumbai Indians,Mumbai Indians,field,Kings XI Punjab
10,2007/08,Bangalore,2008-04-26,League,SR Watson,M Chinnaswamy Stadium,Royal Challengers Bangalore,Rajasthan Royals,Rajasthan Royals,field,Rajasthan Royals
11,2007/08,Chennai,2008-04-26,League,JDP Oram,"MA Chidambaram Stadium, Chepauk",Chennai Super Kings,Kolkata Knight Riders,Kolkata Knight Riders,bat,Chennai Super Kings

In [127]:
# mask = ipl['MatchNumber'] == 'Final'
ipl.sample(5)

,id,season,city,date,match_type,player_of_match,venue,team1,team2,toss_winner,toss_decision,winner,result,result_margin,target_runs,target_overs,super_over,method,umpire1,umpire2
221,501245,2011,Kolkata,2011-05-07,League,Iqbal Abdulla,Eden Gardens,Kolkata Knight Riders,Chennai Super Kings,Chennai Super Kings,bat,Kolkata Knight Riders,runs,10.0,52.0,10.0,N,D/L,Asad Rauf,PR Reiffel
654,1136579,2018,Bengaluru,2018-04-21,League,AB de Villiers,M.Chinnaswamy Stadium,Delhi Daredevils,Royal Challengers Bangalore,Royal Challengers Bangalore,field,Royal Challengers Bangalore,wickets,6.0,175.0,20.0,N,NaN,CB Gaffaney,CK Nandan
199,501223,2011,Delhi,2011-04-23,League,DA Warner,Feroz Shah Kotla,Delhi Daredevils,Kings XI Punjab,Kings XI Punjab,field,Delhi Daredevils,runs,29.0,232.0,20.0,N,NaN,S Asnani,RE Koertzen
950,1359475,2023,Ahmedabad,2023-03-31,League,Rashid Khan,"Narendra Modi Stadium, Ahmedabad",Chennai Super Kings,Gujarat Titans,Gujarat Titans,field,Gujarat Titans,wickets,5.0,179.0,20.0,N,NaN,Nitin Menon,HAS Khalid
224,501248,2011,Chandigarh,2011-05-08,League,R Sharma,"Punjab Cricket Association Stadium, Mohali",Kings XI Punjab,Pune Warriors,Kings XI Punjab,bat,Pune Warriors,wickets,5.0,120.0,20.0,N,NaN,SK Tarapore,RJ Tucker

In [128]:
ipl[ipl['super_over'] == 'Y'].shape[0]

14

In [166]:
ipl[ipl['winner'] == 'Kolkata Knight Riders'].shape[0]
ipl[ipl['city'] == 'Bengaluru'].shape[0]

ipl[(ipl['city'] == 'kolkata') & (ipl['winner'] == 'Chennai Super Kings')].shape[0]
ipl[ipl['toss_winner'] == 'Royal Challengers Bangalore'].shape[0]
ipl[ipl['super_over'] == 'Y'].shape[0]

ipl[ipl['target_runs'] <= 50]

,id,season,city,date,match_type,player_of_match,venue,team1,team2,toss_winner,toss_decision,winner,result,result_margin,target_runs,target_overs,super_over,method,umpire1,umpire2
429,733993,2014,Delhi,2014-05-10,League,DW Steyn,Feroz Shah Kotla,Delhi Daredevils,Sunrisers Hyderabad,Sunrisers Hyderabad,field,Sunrisers Hyderabad,wickets,8.0,43.0,5.0,N,D/L,RM Deshpande,BNJ Oxenford
633,1082648,2017,Bangalore,2017-05-17,Eliminator,NM Coulter-Nile,M Chinnaswamy Stadium,Sunrisers Hyderabad,Kolkata Knight Riders,Kolkata Knight Riders,field,Kolkata Knight Riders,wickets,7.0,48.0,6.0,N,D/L,AK Chaudhary,Nitin Menon

In [173]:
ipl[ipl['target_runs'].between(260 , 300)]

,id,season,city,date,match_type,player_of_match,venue,team1,team2,toss_winner,toss_decision,winner,result,result_margin,target_runs,target_overs,super_over,method,umpire1,umpire2
352,598027,2013,Bangalore,2013-04-23,League,CH Gayle,M Chinnaswamy Stadium,Royal Challengers Bangalore,Pune Warriors,Pune Warriors,field,Royal Challengers Bangalore,runs,130.0,264.0,20.0,N,NaN,Aleem Dar,C Shamshuddin
1031,1422126,2024,Hyderabad,2024-03-27,League,Abhishek Sharma,"Rajiv Gandhi International Stadium, Uppal, Hyd...",Sunrisers Hyderabad,Mumbai Indians,Mumbai Indians,field,Sunrisers Hyderabad,runs,31.0,278.0,20.0,N,NaN,KN Ananthapadmanabhan,UV Gandhe
1039,1422134,2024,Visakhapatnam,2024-04-03,League,SP Narine,Dr. Y.S. Rajasekhara Reddy ACA-VDCA Cricket St...,Kolkata Knight Riders,Delhi Capitals,Kolkata Knight Riders,bat,Kolkata Knight Riders,runs,106.0,273.0,20.0,N,NaN,A Totre,UV Gandhe
1053,1426268,2024,Bengaluru,2024-04-15,League,TM Head,"M Chinnaswamy Stadium, Bengaluru",Sunrisers Hyderabad,Royal Challengers Bengaluru,Royal Challengers Bengaluru,field,Sunrisers Hyderabad,runs,25.0,288.0,20.0,N,NaN,AK Chaudhary,R Pandit
1058,1426273,2024,Delhi,2024-04-20,League,TM Head,"Arun Jaitley Stadium, Delhi",Sunrisers Hyderabad,Delhi Capitals,Delhi Capitals,field,Sunrisers Hyderabad,runs,67.0,267.0,20.0,N,NaN,J Madanagopal,Navdeep Singh
1065,1426280,2024,Kolkata,2024-04-26,League,JM Bairstow,"Eden Gardens, Kolkata",Kolkata Knight Riders,Punjab Kings,Punjab Kings,field,Punjab Kings,wickets,8.0,262.0,20.0,N,NaN,AK Chaudhary,YC Barde

In [179]:
# ipl['winner'].upper()